# Generated by Django 2.1.2 on 2018-10-11 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the company's name (e.g. Galiano Corp, Bravo Supermarket, etc.)", max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text="Enter the company's type (e.g. brokerage, carrier, sender/receiver)", max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an employee role (e.g. broker, dispatcher, driver, manager, owner)', max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.ForeignKey(help_text='Select a type for this company', on_delete=django.db.models.deletion.PROTECT, to='cargo.CompanyType'),
        ),
    ]
