# Generated by Django 2.1.2 on 2018-10-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_auto_20181017_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='assigned',
            field=models.DateTimeField(blank=True, help_text='Represents a timestamp of when the cargo was assigned to the driver', null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='delivered',
            field=models.DateTimeField(blank=True, help_text='Represents a timestamp of when the cargo was delivered', null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='negotiated',
            field=models.DateTimeField(blank=True, help_text='Represents a timestamp of when the cargo was negotiated with the broker', null=True),
        ),
    ]
