# Generated by Django 2.1.2 on 2018-10-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0004_auto_20181017_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['-posted', 'description', '-price']},
        ),
        migrations.AlterModelOptions(
            name='pickuporder',
            options={'ordering': ['-cargo', 'pickup_from']},
        ),
    ]
