# Generated by Django 2.1.2 on 2018-10-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0005_auto_20181018_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['type', 'name']},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['company', 'name']},
        ),
    ]
