# Generated by Django 2.1.2 on 2018-10-25 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0006_auto_20181018_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='broker',
            field=models.ForeignKey(help_text='Represents the employee from a brokerage company posting the cargo', on_delete=django.db.models.deletion.PROTECT, related_name='broker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='dispatcher',
            field=models.ForeignKey(blank=True, help_text='Represents the employee from a carrier company who close the deal with the broker', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatcher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Represents the employee from a carrier company who was assigned for delivering the cargo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver', to=settings.AUTH_USER_MODEL),
        ),
    ]
